In [1]:
from newspaper import Article
from konlpy.tag import Kkma
from konlpy.tag import Okt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import normalize
import numpy as np
import re

kkma = Kkma()
okt = Okt()

text_file = open("./stop_words_file.txt", 'r')

stopwords = [line.rstrip() for line in text_file]

## Crawling

url = 'http://v.media.daum.net/v/20170611192209012?rcmd=r'

article = Article(url, language='ko')
article.download()
article.parse()
sentences = kkma.sentences(article.text)

for idx in range(0, len(sentences)):
  if len(sentences[idx]) <= 10:
    sentences[idx-1] += (' ' + sentences[idx])
    sentences[idx] = ''

print(sentences)

## get_nouns

words = []

for sentence in sentences:
  item_nouns = ' '.join(okt.nouns(str(sentence)))
  words.append(item_nouns)
for i,v in enumerate(words):
  if len(v)<2:
    words.pop(i)
  if v in stopwords:
    words.pop(i)

print(words)

In [13]:
sentences = ['/ 조선 DB “ 신용카드 사용 액이 소득 공제를 받을 수 있는 요건에 못 미치니까 아예 사용 액을 신고하지 않았던 겁니다.', '” 김 상조 공정거래위원장 후보자가 인사 검증 과정에서 신용카드 사용 액을 밝히지 않은 이유를 이렇게 설명했다.', '김 후보자는 카드 사용 액이 총소득의 4분의 1을 넘어야 하는 소득 공제 요건을 충족하지 못한 것이다.', '월급쟁이라면 응당 카드 소득 공제를 받는 것으로 생각하지만 김 후보자처럼 공제를 포기하거나 받지 못하는 사람들도 적지 않다.', '게다가 고 소득자를 중심으로 올해부터 카드 소득 공제 혜택을 줄일 예정이라 카드 공제 받기가 더 까다로 워 진다.', '11일 국세 통계 연보에 따르면, 2015년 기준으로 1733만명인 근로 소득자 중에서 카드 소득 공제를 받은 사람은 49.4% 인 856만명으로 절반에 못 미쳤다.', '그중 소득세가 면세( 免稅) 돼 세금을 내지 않은 257만명을 제외하고 실제로 세금을 낸 사람 중에서 카드 소득 공제를 받은 사람은 599만명으로 전체 월급쟁이의 34.5% 였다.', '◇ 연 봉 5000만원 대가 84% 로 카드 공제 가장 많이 받아 신용카드 소득 공제를 받으려면 총소득의 4분의 1 이상을 카드로 써야 한다.', '4분의 1 문턱에서 1원이라도 모자라면 한 푼도 공제 받을 수 없다.', '수억원 대의 고소득 자일 수록 카드로 소득의 4분의 1 이상을 쓰기 쉽지 않기 때문에 소득이 높을수록 공제를 못 받는 경우가 늘어난다.', '2015년 기준으로 근로 소득세를 내는 사람 중에서 카드 소득 공제를 받는 비율이 가장 많은 소득 구간은 연봉 5000만 ~6000 만원이었다.', '전체의 84% 가 혜택을 봤다.', '연봉 6000만 ~8000 만원 사이에서도 83%, 8000만 ~1 억원 구간은 79% 가 공제를 받았다.', '반면 1억 ~2 억원 사이에서는 공제 받은 사람 비율이 68% 로 줄었고, 2억 ~3 억원인 사람은 31% 만 카드 공제를 받은 것으로 나타났다.', '국세청 관계자는 “ 월급쟁이가 카드를 쓰는 용도가 다들 엇비슷해서 고소득 자라고 해서 카드 사용 액이 월등 하게 늘어나지는 않기 때문에 소득이 높을수록 ‘4 분의 1 문턱’ 을 넘기가 어려워지는 경향이 있다” 고 말했다.', '또 고 소득자들이 외국에 나가 카드를 많이 사용하지만, 해외에서의 카드 사용 액을 일절 공제해 주지 않는 점도 영향이 있는 것으로 분석된다.', '◇ 소득 낮은 부부는 한 사람 명의의 카드 써야 유리 소득이 연 5000만원에 못 미치는 서민층에서도 카드 공제를 받는 사람들의 비율이 낮아 지는 경향을 보인다.', '연봉 4000만원 대는 81%, 3000만원 대는 73%, 2000만원 대는 55% 만 카드 소득 공제를 받은 것으로 나타났다.', '이런 현상이 나타나는 이유는 우선 저소득층일수록 허리띠를 졸라매는 경향이 있어 ‘4 분의 1 문턱’ 을 넘지 못하는 경우가 상당하기 때문인 것으로 추정된다.', '또 소득이 넉넉하지 않은 맞벌이의 경우 한 사람 명의로 카드를 발급 받아 한 사람의 카드 사용 액이 ‘4 분의 1 문턱’ 을 넘도록 몰아주고, 나머지 배우자는 카드 소득 공제를 포기하는 절세 노하우를 보여주는 사례도 많다 고 국세청 관계자들은 설명했다.', '서울지역의 한 세무사는 “ 부부가 각자 명의로 카드를 쓰다가 둘 다 ‘4 분의 1 문턱’ 을 못 넘겨 안 내도 될 세금을 더 내는 경우가 있으니 주의해야 한다” 고 말했다.', '2015년 기준으로 카드 소득 공제를 받은 599만명은 평균 245만원을 공제 받은 것으로 나타났다.', '300만원인 공제한도를 채우지 못한 사람들이 적지 않다는 뜻이다.', '카드 소득 공제는 4분의 1 문턱을 초과하는 액수에 대해 신용카드는 15%, 체크카드는 30%에 해당하는 액수를 300만원 한도로 공제하는 방식이다.', '전통시장에서 결제한 금액과 대중 교통비에 대해서는 각각 100 만원씩 공제 한도가 더 늘어난다.', '◇ 연 봉 1억 2000만원 이상은 올해부터, 7000만원 이상은 내년부터 공제한도 축소 신용카드 소득 공제는 올해부터 순차적으로 한도가 줄어들게 되므로 관련 제도 변화를 유심히 살펴볼 필요가 있다.', '고소득 자의 공제 폭을 줄여 실질적인 근로 소득세 증세( 增稅) 가 예고돼 있다.', '우선 연소득 1억 2000만원이 넘는 월급쟁이는 올해 사용 분부터 공제한도가 기존 300만원에서 200만원으로 줄어든다.', '내년 초 연말 정산 때 돌려받는 세금이 수십만원 정도 줄어들거나, 토해 내는 세금이 수십만원 늘어난다는 뜻이다.', '연봉 7000만 ~1 억 2000만원 근로자의 공제 한도는 내년 사용 분부터 300만원에서 250만원으로 축소될 전망이다.', '연봉 7000만 ~1 억 2000만원인 근로자에 대해 정부는 2019년부터 한도를 축소하기로 했지만 지난해 국회가 1년 앞당겨 실시하기로 결정했다.']
words = ['조선 신용카드 사용 액 소득 공제 수 요건 못 아예 사용 액 신고', '김 상조 공정 거래 위원장 후보자 인사 검증 과정 신용카드 사용 액 이유 설명', '김 후보자 카드 사용 액 소득 소득 공제 요건 충족 못 것', '월급쟁이 라면 응당 카드 소득 공제 것 생각 김 후보자 공제 포기 거나 사람 적지', '게다가 고 소득 중심 올해 카드 소득 공제 혜택 예정 카드 공제 더 워', '국세 통계 연보 기준 근로 소득 중 카드 소득 공제 사람 인 절반 못', '소득세 면세 세금 내지 제외 실제 세금 사람 중 카드 소득 공제 사람 전체 월급쟁이', '연 봉 대가 로 카드 공제 가장 신용카드 소득 공제 소득 이상 카드', '문턱 푼 공제 수', '억원 대의 소득 자일 수록 카드 소득 이상 쓰기 때문 소득 공제 못 경우', '기준 근로 소득세 사람 중 카드 소득 공제 비율 가장 소득 구간 연봉 만원', '전체 혜택', '연봉 만원 사이 억원 구간 공제', '반면 억원 사이 공제 사람 비율 로 억원 사람 만 카드 공제 것', '국세청 관계자 월급쟁이 카드 용도 소득 카드 사용 액 월등 때문 소득 분 문턱 경향 고 말', '또 고 소득 외국 카드 사용 해외 카드 사용 액 일절 공제 주지 점도 영향 것 분석', '소득 부부 사람 명의 카드 유리 소득 연 못 서민 층 카드 공제 사람 비율 경향', '연봉 만 카드 소득 공제 것', '현상 이유 우선 소득 층 허리띠 졸라 경향 분 문턱 경우 때문 것 추정', '또 소득 맞벌이 경우 사람 명의 카드 발급 사람 카드 사용 액 분 문턱 나머지 배우자 카드 소득 공제 포기 절세 노하우 사례 고 국세청 관계자 설명', '지역 세무사 부부 각자 명의 카드 둘 분 문턱 못 안 세금 더 경우 주의 고 말', '기준 카드 소득 공제 평균 공제 것', '한도 못 사람 적지 뜻', '카드 소득 공제 문턱 초과 액수 대해 신용카드 체크카드 해당 액수 한도 공제 방식', '전통 시장 결제 금액 대중 교통비 대해 각각 만원 공제 한도 더', '연 봉 이상은 올해 이상은 내년 공제 한도 축소 신용카드 소득 공제 올해 순차 한도 관련 제도 변화 유심 필요', '소득 자의 공제 폭 실질 근로 소득세 증세 예고', '우선 소득 월급쟁이 올해 사용 분 한도 기존', '내년 초 연말 정산 때 세금 만원 정도 토 세금 만원 뜻', '연봉 억 근로자 공제 한도 내년 사용 분 축소 전망', '연봉 억 근로자 대해 정부 한도 축소 지난해 국회 실시 결정']

## GraphMatrix

In [6]:
tfidf = TfidfVectorizer()
cnt_vec = CountVectorizer()
sentence_graph = []

 - build_sent_graph

In [7]:
tfidf_mat = tfidf.fit_transform(words).toarray()
sentence_graph = np.dot(tfidf_mat, tfidf_mat.T)

print(sentence_graph)

[[1.         0.15709804 0.40929242 0.05629368 0.08704503 0.06499458
  0.03337226 0.19149912 0.06713909 0.07797693 0.06498767 0.
  0.02726381 0.03767624 0.14925606 0.22769726 0.06026261 0.11182509
  0.02035407 0.11556674 0.         0.10115822 0.         0.11067701
  0.01712927 0.08901581 0.04589321 0.17775783 0.         0.16262535
  0.        ]
 [0.15709804 1.         0.16815557 0.07400157 0.         0.
  0.         0.07163736 0.         0.         0.         0.
  0.         0.         0.04129871 0.07409218 0.         0.
  0.08803991 0.09116927 0.         0.         0.         0.04798298
  0.         0.03859197 0.         0.05725404 0.         0.053467
  0.        ]
 [0.40929242 0.16815557 1.         0.25258102 0.24305916 0.17606613
  0.09318663 0.27514584 0.08568512 0.20808669 0.17604742 0.
  0.03479497 0.08180215 0.24174991 0.25114496 0.19610399 0.31225347
  0.05195306 0.20555415 0.03354113 0.23364769 0.         0.11181369
  0.02186094 0.06774578 0.08979004 0.16925602 0.         0.118

 - build_words_graph

In [8]:
data = cnt_vec.fit_transform(words).toarray()
cnt_vec_mat = normalize(data, axis=0)
vocab = cnt_vec.vocabulary_

words_graph = np.dot(cnt_vec_mat.T, cnt_vec_mat)
idx2word = {vocab[word] : word for word in vocab}

print(words_graph)
print(idx2word)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
{109: '조선', 65: '신용카드', 51: '사용', 59: '소득', 12: '공제', 81: '요건', 70: '아예', 64: '신고', 53: '상조', 11: '공정', 4: '거래', 86: '위원장', 133: '후보자', 93: '인사', 5: '검증', 13: '과정', 92: '이유', 56: '설명', 122: '카드', 121: '충족', 84: '월급쟁이', 35: '라면', 89: '응당', 54: '생각', 125: '포기', 3: '거나', 49: '사람', 97: '적지', 6: '게다가', 113: '중심', 79: '올해', 132: '혜택', 78: '예정', 18: '국세', 123: '통계', 74: '연보', 25: '기준', 21: '근로', 101: '절반', 60: '소득세', 38: '면세', 57: '세금', 28: '내지', 108: '제외', 67: '실제', 99: '전체', 30: '대가', 0: '가장', 90: '이상', 40: '문턱', 72: '억원', 31: '대의', 96: '자일', 61: '수록', 69: '쓰기', 34: '때문', 9: '경우', 48: '비율', 17: '구간', 75: '연봉', 36: '만원', 52: '사이', 41: '반면', 19: '국세청', 14: '관계자', 82: '용도', 85: '월등', 10: '경향', 80: '외국', 129: '해외', 94: '일절', 112: '주지', 103: '점도', 76: '영향', 47: '분석', 46: '부부', 39: '명의', 87: '유리', 55: '서민', 131: '현상', 83: '우선', 130: '허리띠', 110

## Rank

 - sentence graph

In [9]:
A = sentence_graph
d = 0.85
matrix_size = A.shape[0]

for id in range(matrix_size):
      A[id, id] = 0 # diagonal 부분을 0으로
      link_sum = np.sum(A[:,id]) # A[:, id] = A[:][id]
      if link_sum != 0:
            A[:, id] /= link_sum
      A[:, id] *= -d
      A[id, id] = 1

B = (1-d) * np.ones((matrix_size, 1))
ranks = np.linalg.solve(A, B) # 연립방정식 Ax = b

sentence_graph_idx = {idx: r[0] for idx, r in enumerate(ranks)}
print(sentence_graph_idx)

sorted_sentence_rank_idx = sorted(sentence_graph_idx, key=lambda k: sentence_graph_idx[k], reverse=True)
print(sorted_sentence_rank_idx)

1
2
3
4
{0: 0.9032943235512652, 1: 0.4213925573782945, 2: 1.3595677293092279, 3: 1.1315859377120738, 4: 1.3869143781857531, 5: 1.131099518296948, 6: 1.1615598580315338, 7: 1.4655858825537653, 8: 0.964244389894159, 9: 1.1296895039054569, 10: 1.580120544961152, 11: 0.2769280389641702, 12: 0.8918339574781374, 13: 1.13107536584435, 14: 1.2454605373929712, 15: 0.9405685978515068, 16: 1.3929488470528086, 17: 1.7171810591902055, 18: 0.648616607132012, 19: 1.3541788063857114, 20: 0.6643799206366394, 21: 1.310707726100585, 22: 0.7495058511253502, 23: 1.0127005361224972, 24: 0.5631131607025841, 25: 0.8657787551914167, 26: 0.6388148915777341, 27: 0.9428010844467573, 28: 0.4801405949776003, 29: 1.0079845937013356, 30: 0.530226444345996}
[17, 10, 7, 16, 4, 2, 19, 21, 14, 6, 3, 5, 13, 9, 23, 29, 8, 27, 15, 0, 12, 25, 22, 20, 18, 26, 24, 30, 28, 1, 11]


 - word graph

In [10]:
A = words_graph
d = 0.85
matrix_size = A.shape[0]

for id in range(matrix_size):
      A[id, id] = 0 # diagonal 부분을 0으로
      link_sum = np.sum(A[:,id]) # A[:, id] = A[:][id]
      if link_sum != 0:
            A[:, id] /= link_sum
      A[:, id] *= -d
      A[id, id] = 1

B = (1-d) * np.ones((matrix_size, 1))
ranks = np.linalg.solve(A, B) # 연립방정식 Ax = b

words_graph_idx = {idx: r[0] for idx, r in enumerate(ranks)}
print(words_graph_idx)

sorted_words_rank_idx = sorted(words_graph_idx, key=lambda k: words_graph_idx[k], reverse=True)
print(sorted_words_rank_idx)

{0: 0.7824713313970741, 1: 0.9562093733572655, 2: 0.7594423160537754, 3: 0.8170633284152349, 4: 0.9847324943648585, 5: 0.9847324943648587, 6: 0.6639583624454188, 7: 0.8775031595214318, 8: 0.9562093733572657, 9: 1.7775737775991798, 10: 1.219602365185432, 11: 0.9847324943648585, 12: 2.8359528332008983, 13: 0.9847324943648587, 14: 1.3290308235171173, 15: 1.0844825552880974, 16: 0.956209373357266, 17: 0.7096362674016707, 18: 0.7687939730514537, 19: 1.3290308235171178, 20: 0.8775031595214319, 21: 1.2480713232639582, 22: 0.9516162625670743, 23: 0.9562093733572652, 24: 0.3917364460606458, 25: 1.013287692517498, 26: 1.2245416472513417, 27: 1.2691396178457375, 28: 0.8695482666510905, 29: 1.2245416472513417, 30: 0.45105324344765957, 31: 0.8053490171058034, 32: 0.9562093733572656, 33: 1.5127971395384003, 34: 1.3136489998091658, 35: 0.8170633284152347, 36: 1.229087106706024, 37: 1.2245416472513415, 38: 0.8695482666510901, 39: 1.495189006950352, 40: 1.7471375864949854, 41: 0.4999784040073305, 42: 1

 - summarize

In [14]:
sent_num=3
summary = []
index=[]

for idx in sorted_sentence_rank_idx[:sent_num]:
      index.append(idx)

index.sort()
for idx in index:
      summary.append(sentences[idx])

 - keywords

In [15]:
word_num=10
keywords = []
index=[]

for idx in sorted_words_rank_idx[:word_num]:
      index.append(idx)
    
#index.sort()
for idx in index:
      keywords.append(idx2word[idx])

In [27]:
count = 0

for row in summary:
    print(row)
    print()
    count = count + 1
    if(count > 3):
        break

print('keywords :',keywords)

◇ 연 봉 5000만원 대가 84% 로 카드 공제 가장 많이 받아 신용카드 소득 공제를 받으려면 총소득의 4분의 1 이상을 카드로 써야 한다.

2015년 기준으로 근로 소득세를 내는 사람 중에서 카드 소득 공제를 받는 비율이 가장 많은 소득 구간은 연봉 5000만 ~6000 만원이었다.

연봉 4000만원 대는 81%, 3000만원 대는 73%, 2000만원 대는 55% 만 카드 소득 공제를 받은 것으로 나타났다.

keywords : ['소득', '공제', '카드', '사람', '사용', '한도', '경우', '신용카드', '문턱', '설명']
