# Python 기초

### python version

In [1]:
# python system 기능을 사용하기 위해 사용하는 라이브러리
import sys

# "Python version" 이라는 문자열을 출력
print("Python version")

# sys.version에 저장되어있는 값을 출력
print (sys.version)
 
# "Version info." 이라는 문자열을 출력
print("Version info.")

# sys.version_info에 저장되어있는 값을 출력
print (sys.version_info)

Python version
3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
Version info.
sys.version_info(major=3, minor=7, micro=9, releaselevel='final', serial=0)


## 변수

### 문자열 출력

In [2]:
print('딥러닝 활용')
print('셀 실행은 shift + Enter')

딥러닝 활용
셀 실행은 shift + Enter


### 문자열 변수 할당

In [3]:
title ='딥러닝 활용'
command_string='셀 실행은 shift + Enter'
print(title)
print(command_string)

딥러닝 활용
셀 실행은 shift + Enter


### 변수이름 명명 법
- class 이름 : pascal case(파스칼 표기법)

  `Title, CommandString`
- 상수 : 대문자

  `TITLE, COMMAND_STRING`
- 변수 or 함수 : snake case or pothole case

  `title, title_string`

## 배열, numpy, pandas

### 배열(list)

In [4]:
# 배열의 선언

sample_array = ['a', 'b', 'c', 'd', 'e', 'f']

In [5]:
print(sample_array)

['a', 'b', 'c', 'd', 'e', 'f']


In [6]:
#배열의 선언 & 원소 추가

sample_array2 = []
sample_array2.append('a')
sample_array2.append('b')
sample_array2.append('c')
sample_array2.append('d')
sample_array2.append('e')
sample_array2.append('f')

In [7]:
print(sample_array2)

['a', 'b', 'c', 'd', 'e', 'f']


In [8]:
# 배열의 길이

len(sample_array2)

6

In [9]:
# 배열의 정렬
# 배열.sort() -> 오름차순 (Default)
# 배열.sort(reverse=True) -> 내림차순 (False = 오름차순)

sample_array2.sort(reverse=True)

In [10]:
print(sample_array2)

['f', 'e', 'd', 'c', 'b', 'a']


### 배열의 색인

In [11]:
# [0:3] : 0 <= 색인 < 3
print(sample_array[0:3])

# [3:] : 3<= 색인 <= 끝
print(sample_array[3:])

# [:3] : 시작 <= 색인 < 3
print(sample_array[:3])

['a', 'b', 'c']
['d', 'e', 'f']
['a', 'b', 'c']


### 배열 정보

In [12]:
# 형변환(type cast)
# 문자열과 다른 유형의 변수의 연산은 다른 유형의 변수를 문자열로 변경한다.

array_length = len(sample_array)
array_type = type(sample_array)

# 배열의 길이
print('length : ' + str(array_length))

# 변수의 타입
print('type: ' + str(array_type))

print('type: ' + str(type(command_string)))

length : 6
type: <class 'list'>
type: <class 'str'>


### range(start,end)
start, end까지 값을 가지는 range

list(range(start,end)) 값을 통해서 array값을 생성

In [13]:
# 0~20의 숫자릴 리스트에 삽입

simple_array = list(range(0,20))

In [14]:
print(simple_array)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


### numpy
대부분의 python 데이터는 numpy 데이터로 처리된다.

In [15]:
# np 라는 이름으로 사용한다(관례)

import numpy as np

In [16]:
# 위에서 생성한 list를 사용해 array 정의

np_array = np.array(simple_array)

In [17]:
np_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
# array의 크기를 확인

np_array.shape

(20,)

In [19]:
# array의 타입 확인 (?)
print(type(np_array))

# array의 데이터 타입 확인
np_array.dtype

<class 'numpy.ndarray'>


dtype('int32')

In [20]:
# 1차원 array
arr1 = np.array([1,2,3])
print('1차원\n',arr1, '\n\n')

# 2차원 array
arr2 = np.array([[1,2,3],[1,2,3]])
print('2차원\n',arr2,'\n\n')

# 3차원 array
arr3 = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print('3차원 \n',arr3)

1차원
 [1 2 3] 


2차원
 [[1 2 3]
 [1 2 3]] 


3차원 
 [[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


numpy 정의 함수  
  * np.zeros(), np.ones(), np.arange()

In [21]:
# np.zeors() : 인자로 받은 크기만큼, 모든 요소가 0인 array 생성

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
# np.ones() : 인자로 받은 크기만큼, 모든 요소가 1인 array 생성

np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
# np.arange() : 인자로 받은 크기만큼 1씩 증가하는 array 생성
# 하나의 인자 -> 0 ~ (인자 - 1) / 두 개의 인자 -> 인자1 ~ (인자2 - 1)

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(3,5)

array([3, 4])

Array 연산  
  * 기본적으로 array끼리 크기가 동일해야 함

In [27]:
x = np.array(range(1,4))

In [28]:
x

array([1, 2, 3])

In [29]:
y = np.array(range(5,8))

In [30]:
y

array([5, 6, 7])

In [31]:
x+y

array([ 6,  8, 10])

In [32]:
x*y

array([ 5, 12, 21])

In [33]:
x*2*y

array([10, 24, 42])

Array 브로드캐스팅(Broadcasting)  
  * 크기가 다른 array의 연산을 제공
  * array + 스칼라 값(상수)인 경우
  * 차원이 다르지만 행/열의 개수가 같은 경우
    * 이때 열/행의 개수는 1이어야 확장이 가능 

In [34]:
ary1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(ary1,'\n')

ary2 = np.array([[4],[6],[8]])
print(ary2,'\n')

print(ary1+ary2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[4]
 [6]
 [8]] 

[[ 5  6  7  8]
 [11 12 13 14]
 [17 18 19 20]]


Array 인덱싱  
  * 1차원

In [35]:
# 1차원 배열 생성
arr1 = np.arange(10)

# array의 1번째 원소
print(arr1[1])

# 1번째부터 5번째 원소
print(arr1[1:5])

# 모든 원소
print(arr1[:])

1
[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


  * 1차원이 아닌 경우

In [36]:
# 2차원 배열 생성
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# 1차원이 아닌 경우, 차원의 개수만큼 인자를 입력해야 함
print(arr2[0,0])

# 2행의 3번째 원소
print(arr2[2,3])

# 2행의 모든 원소
print(arr2[2,:])

# 모든 행의 3번째 원소
print(arr2[:,3])

1
12
[ 9 10 11 12]
[ 4  8 12]


Array Boolean 인덱싱(마스크)  
  * boolean 인덱싱을 통해, 원하는 원소만을 보여줄 수 있음

In [37]:
names = np.array(['Kim', 'Kim', 'Hoo','Jeong','woman','Kim','22','Kim'])
print(names,'\n')

# np.random 함수를 사용해, 난수 생성
data = np.random.rand(8,4)
print(data)

['Kim' 'Kim' 'Hoo' 'Jeong' 'woman' 'Kim' '22' 'Kim'] 

[[0.6186156  0.39221665 0.04080922 0.11753323]
 [0.83000709 0.4668394  0.6490857  0.70440535]
 [0.62749346 0.3263693  0.83117066 0.41961748]
 [0.44552161 0.74228304 0.18339153 0.33337113]
 [0.81040857 0.56784962 0.98615035 0.00574617]
 [0.39602452 0.55969188 0.16540082 0.58794943]
 [0.74925881 0.12681063 0.46470231 0.96157132]
 [0.50175472 0.24763934 0.2264423  0.98064603]]


    - names의 각 원소가 data의 각 행과 연결된다고 가정
    - names의 원소가 'Kim'인 행의 data만 보고싶을 경우, 다음과 같이 마스크 사용

In [38]:
# 원소가 'Kim'일 때, 이에 대한 mask 생성
names_mask = (names == 'Kim')
print(names_mask,'\n')

# 마스크가 해당하는 행의 모든 원소
print(data[names_mask, :])

[ True  True False False False  True False  True] 

[[0.6186156  0.39221665 0.04080922 0.11753323]
 [0.83000709 0.4668394  0.6490857  0.70440535]
 [0.39602452 0.55969188 0.16540082 0.58794943]
 [0.50175472 0.24763934 0.2264423  0.98064603]]


In [39]:
# 원소가 'Kim'인 행의 데이터만 출력
print(data[names == 'Kim'],'\n')

# 논리 연산을 사용해, 원소가 'Kim' 또는 'Hoo'인 행의 데이터 출력
print(data[(names == 'Kim') | (names == 'Hoo'), :])

[[0.6186156  0.39221665 0.04080922 0.11753323]
 [0.83000709 0.4668394  0.6490857  0.70440535]
 [0.39602452 0.55969188 0.16540082 0.58794943]
 [0.50175472 0.24763934 0.2264423  0.98064603]] 

[[0.6186156  0.39221665 0.04080922 0.11753323]
 [0.83000709 0.4668394  0.6490857  0.70440535]
 [0.62749346 0.3263693  0.83117066 0.41961748]
 [0.39602452 0.55969188 0.16540082 0.58794943]
 [0.50175472 0.24763934 0.2264423  0.98064603]]


    - mask 활용

In [40]:
# 마스크 생성
# data array에서 모든 행의 0번째 열중, 0.5보다 작은 원소의 boolean 값

mask = data[:,0]<0.5
mask

array([False, False, False,  True, False,  True, False, False])

In [41]:
# 위에서 생성한 마스크를 사용해, 0번째 열 중에서 값이 0.5보다 작은 행 출력
data[mask, :]

array([[0.44552161, 0.74228304, 0.18339153, 0.33337113],
       [0.39602452, 0.55969188, 0.16540082, 0.58794943]])

In [42]:
# 0번째 열 중에서 0.5보다 작은 행의 2, 3번째 열의 값을 -1로 변경
data[mask, 2:4] = -1
data

array([[ 0.6186156 ,  0.39221665,  0.04080922,  0.11753323],
       [ 0.83000709,  0.4668394 ,  0.6490857 ,  0.70440535],
       [ 0.62749346,  0.3263693 ,  0.83117066,  0.41961748],
       [ 0.44552161,  0.74228304, -1.        , -1.        ],
       [ 0.81040857,  0.56784962,  0.98615035,  0.00574617],
       [ 0.39602452,  0.55969188, -1.        , -1.        ],
       [ 0.74925881,  0.12681063,  0.46470231,  0.96157132],
       [ 0.50175472,  0.24763934,  0.2264423 ,  0.98064603]])

Array 적용 함수
  * 구글링 하면서 ㄱ

In [43]:
# 난수
f_arr = np.random.rand(5,3)

# 각 성분의 절대값
print(np.abs(f_arr), '\n')

# 각 성분의 제곱근 (제곱은 square)
print(np.sqrt(f_arr), '\n')

# 각 성분을 소수 첫 번째 자리에서 올림 (반대는 floor)
print(np.ceil(f_arr))

[[0.13662286 0.86748233 0.670893  ]
 [0.96363495 0.57334322 0.87951414]
 [0.57169924 0.93055328 0.46997525]
 [0.82231103 0.93210572 0.74877588]
 [0.7818933  0.09953493 0.77589589]] 

[[0.3696253  0.93138731 0.81908058]
 [0.9816491  0.75719431 0.93782415]
 [0.75610796 0.9646519  0.68554741]
 [0.90681367 0.96545622 0.86531837]
 [0.88424731 0.31549157 0.88084953]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


- 차원 변경
  - reshape(n,m) : row(행) n, column(열) m의 차원으로 변경
  - reshape(-1, m) : column m 차원으로 row를 자동으로 변경
  - reshape(-1,) : 1차원 으로 변경

In [44]:
np_4_5 = np_array.reshape(4,5)

In [45]:
np_4_5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
np_1_20 = np_4_5.reshape(1, 20)

In [47]:
np_1_20

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [48]:
np_1 = np_1_20.reshape(-1,)

In [49]:
np_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### pandas
데이터 분석 및 조회를 쉽게 사용 하는 라이브러리, 
표 형태로 이용한다
- Series : 1차원
- DataFrame : 2차원
- Panel : 3차원

In [50]:
# pd라는 이름으로 사용한다(관례상)
import pandas as pd

- series

In [51]:
# Series 생성
sr = pd.Series(['A', 'B+', 'A+', 'B'])
print(sr)

0     A
1    B+
2    A+
3     B
dtype: object


In [52]:
# Series의 값만 확인
print(sr.values)

['A' 'B+' 'A+' 'B']


In [53]:
# Series의 자료형 확인
type(sr.values)

numpy.ndarray

In [54]:
# Series의 index 설정 가능
sr1 = pd.Series(['90','80','70','60'], index = ['국어','수학','영어','과학'])
print(sr1)

국어    90
수학    80
영어    70
과학    60
dtype: object


In [55]:
# index만 확인
print(sr1.index)

Index(['국어', '수학', '영어', '과학'], dtype='object')


  * dictionary 자료형을 Series의 data로 만들 수 있음
  * dictionary의 key가 Series의 index가 됨

In [56]:
sdata = {'Kim' : 10, 'Hoo' : 20, 'Jeong' : 30, '22' : 40}
sr3 = pd.Series(sdata)
sr3

Kim      10
Hoo      20
Jeong    30
22       40
dtype: int64

In [57]:
sr3.name = 'Name'
sr3.index.name = "Profile"
sr3

Profile
Kim      10
Hoo      20
Jeong    30
22       40
Name: Name, dtype: int64

In [58]:
# index만 변경하기
sr3.index = ['A', 'B', 'C', 'D']
sr3

A    10
B    20
C    30
D    40
Name: Name, dtype: int64

- dataframe

In [59]:
# Data Frame 생성
# Data Frame에 들어갈 data를 정의할 때, dictionary나 array로 정의할 수 있음

data = [
    ['1', 'a', 90.72], 
    ['2', 'b', 78.09], 
    ['3', 'c', 98.43], 
    ['4', 'd', 64.19], 
    ['5', 'e', 81.30],
    ['6', 'f', 99.14],
]
df = pd.DataFrame(data)
df

0  1      2
0  1  a  90.72
1  2  b  78.09
2  3  c  98.43
3  4  d  64.19
4  5  e  81.30
5  6  f  99.14

In [60]:
# 행과 열의 구조를 가진 data가 생성 됨

# 행 방향의 index
print(df.index,'\n')

# 열 방향의 index
print(df.columns,'\n')

# data 얻기
print(df.values)

RangeIndex(start=0, stop=6, step=1) 

RangeIndex(start=0, stop=3, step=1) 

[['1' 'a' 90.72]
 ['2' 'b' 78.09]
 ['3' 'c' 98.43]
 ['4' 'd' 64.19]
 ['5' 'e' 81.3]
 ['6' 'f' 99.14]]


In [61]:
# Data Frame을 만들며, index와 columns를 설정할 수 있음

df = pd.DataFrame(data, columns=['학번', '이름', '점수'], index=['One', 'Two', 'Three', 'Four', 'Five', 'Six'])
df

학번 이름     점수
One    1  a  90.72
Two    2  b  78.09
Three  3  c  98.43
Four   4  d  64.19
Five   5  e  81.30
Six    6  f  99.14

In [62]:
df.head(3)

학번 이름     점수
One    1  a  90.72
Two    2  b  78.09
Three  3  c  98.43

In [63]:
df.tail(3)

학번 이름     점수
Four  4  d  64.19
Five  5  e  81.30
Six   6  f  99.14

In [64]:
df['이름']

One      a
Two      b
Three    c
Four     d
Five     e
Six      f
Name: 이름, dtype: object

- 외부 데이터 읽기

In [65]:
df=pd.read_json('sample_data/anscombe.json')

ValueError: Expected object or value

In [66]:
df

학번 이름     점수
One    1  a  90.72
Two    2  b  78.09
Three  3  c  98.43
Four   4  d  64.19
Five   5  e  81.30
Six    6  f  99.14

In [67]:
df1 = pd.read_csv('sample_data/california_housing_train.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'sample_data/california_housing_train.csv'

In [68]:
df1

NameError: name 'df1' is not defined

- 조건 검색

In [ ]:
df1.loc[df1['median_house_value'] > 100000 ]

In [ ]:
df1.loc[(df1['median_house_value'] > 100000) & (df1['housing_median_age'] < 20.0) ]

## Tuple
- `(val1, val2)`
- list와 다른점 : 값을 변경할 수 없다.


In [ ]:
|sample_tuple = ()
sample_tuple = 1,2,3
print(sample_tuple)

### packing, unpacking
- packing
  - `sample_tuple = 1,2,3`
- unpacking
  - `result_1, result_2, result_3 = sample_tuple`

In [ ]:
result_1, result_2, result_3 = sample_tuple

In [ ]:
result_1, result_2, result_3 

## dictionary
- `sample_dic = {key1:value1, key2:value2, ...}`
- `value1 = sample_dic['key1']`
- `sample_dic['key9']=value9`
- `del sample_dic['key9']`

In [ ]:
sample_dic = {1:'a', 2:'b', 3:'c'}

In [ ]:
print(sample_dic)

In [ ]:
print(sample_dic[1])

In [ ]:
sample_dic[9] = 'z'

In [ ]:
print(sample_dic)

In [ ]:
del sample_dic[9]

In [ ]:
print(sample_dic)

###  function
  - `sample_dic.values()`
  - `sample_dic.keys()`
  - `sample_dic.items()`
  - `sample_dic.get(1)`
  - `3 in sample_dic`
  - `9 in sample_dic`

In [ ]:
sample_dic.values()

In [ ]:
sample_dic.keys()

In [ ]:
sample_dic.items()

In [ ]:
sample_dic.get(1)

In [ ]:
3 in sample_dic

In [ ]:
9 in sample_dic

## 제어문

### if문
``` 
if(condition) :
    print(condition)
else :
    print(condition)
```

In [ ]:
if 3 in sample_dic:
    print('3 in the sample_dic')
else:
    print('3 not in the sample_dic')

### while
```
condition = True
index = 0
while condition:
    print(index)
    index += 1
    if index == 5:
        condition = True
```

In [ ]:
condition = True
index = 0
while condition:
    print(index)
    index += 1
    if index == 5:
        condition = False


### for
```
sample_list = [1,2,3,4,5,6,7,8,9]
for i in sample_list:
    print(i)  
```

In [ ]:
sample_list = [1,2,3,4,5,6,7,8,9]
for i in sample_list:
    print(i)

```
sample_tuple_list = [(1,2), (3,4), (5,6), (7,8), (9, 10)]
for (i,j) in sample_tuple_list:
    print(i, j)
```

In [ ]:
sample_tuple_list = [(1,2), (3,4), (5,6), (7,8), (9, 10)]
for (i,j) in sample_tuple_list:
    print(i, j)


```
for i in range(2,19):
    for j in range(2, 19):
          print("2d*2d=4d" % (i, j, i*j) 
    
```

In [ ]:
for i in range(2,19):
    for j in range(2, 19):
          print("%2d*%2d=%4d" %  (i, j, i*j ) )

# 실습

- 명령구문아래에 동일한 코드 paragraph를 추가하여 실행해봅니다